# Generated by Django 3.0.1 on 2019-12-31 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('tutorial_link', models.CharField(blank=True, max_length=1000)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('exercise_list', models.ManyToManyField(to='muscle.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('workout_list', models.ManyToManyField(to='muscle.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_muscle', to='muscle.Muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_muscle', to='muscle.Muscle'),
        ),
    ]
