# Generated by Django 3.0.1 on 2019-12-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('exercise_list', models.ManyToManyField(to='exercise.Exercise')),
            ],
        ),
    ]
