# Generated by Django 3.0.1 on 2019-12-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muscle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('tutorial_link', models.CharField(blank=True, max_length=1000)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('primary_muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_muscle', to='muscle.Muscle')),
                ('secondary_muscle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_muscle', to='muscle.Muscle')),
            ],
        ),
    ]
